/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#712618",
        "on-primary": "#ffffff",
        "primary-container": "#8f3c2c",
        "on-primary-container": "#ffbbad",
        "primary-fixed": "#ffdad3",
        "primary-fixed-dim": "#ffb4a5",
        "on-primary-fixed": "#3f0400",
        "on-primary-fixed-variant": "#7b2d1f",
        "inverse-primary": "#ffb4a5",

        "secondary": "#556254",
        "on-secondary": "#ffffff",
        "secondary-container": "#d6e4d2",
        "on-secondary-container": "#596658",
        "secondary-fixed": "#d9e6d5",
        "secondary-fixed-dim": "#bdcab9",
        "on-secondary-fixed": "#131e13",
        "on-secondary-fixed-variant": "#3e4a3d",

        "tertiary": "#593711",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#744e26",
        "on-tertiary-container": "#f6c28f",
        "tertiary-fixed": "#ffdcbd",
        "tertiary-fixed-dim": "#f0bd8b",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-fixed-variant": "#623f18",

        "surface": "#fcf9f5",
        "surface-dim": "#dcdad6",
        "surface-bright": "#fcf9f5",
        "surface-variant": "#e5e2de",
        "surface-tint": "#9a4433",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ef",
        "surface-container": "#f0edea",
        "surface-container-high": "#ebe8e4",
        "surface-container-highest": "#e5e2de",

        "on-surface": "#1c1c1a",
        "on-surface-variant": "#55423f",
        "inverse-surface": "#31302e",
        "inverse-on-surface": "#f3f0ec",
        "background": "#fcf9f5",
        "on-background": "#1c1c1a",

        "outline": "#88726e",
        "outline-variant": "#dbc1bb",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "full": "9999px",
      },
      spacing: {
        "margin": "1.25rem",
        "margin-desktop": "3rem",
        "gutter": "1.5rem",
        "gutter-desktop": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "display-xl": ["'Playfair Display'", "serif"],
        "display-lg": ["'Playfair Display'", "serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "caption": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-xl-mobile": ["'Playfair Display'", "serif"],
        "display-lg-mobile": ["'Playfair Display'", "serif"],
      },
      fontSize: {
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-xl-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
