/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fbf8fc",
        "surface-dim": "#dcd9dd",
        "surface-bright": "#fbf8fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f2f7",
        "surface-container": "#f0edf1",
        "surface-container-high": "#eae7eb",
        "surface-container-highest": "#e4e1e6",
        "surface-variant": "#e4e1e6",
        "surface-tint": "#5f5e60",

        "on-surface": "#1b1b1e",
        "on-surface-variant": "#47464a",
        "inverse-surface": "#303033",
        "inverse-on-surface": "#f3f0f4",
        "background": "#fbf8fc",
        "on-background": "#1b1b1e",

        "outline": "#78767b",
        "outline-variant": "#c8c5ca",

        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1d",
        "on-primary-container": "#858386",
        "inverse-primary": "#c8c6c8",
        "primary-fixed": "#e5e1e4",
        "primary-fixed-dim": "#c8c6c8",
        "on-primary-fixed": "#1c1b1d",
        "on-primary-fixed-variant": "#474649",

        "secondary": "#5d5e66",
        "on-secondary": "#ffffff",
        "secondary-container": "#e3e1ec",
        "on-secondary-container": "#63646c",
        "secondary-fixed": "#e3e1ec",
        "secondary-fixed-dim": "#c6c5cf",
        "on-secondary-fixed": "#1a1b22",
        "on-secondary-fixed-variant": "#46464e",

        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#002114",
        "on-tertiary-container": "#069669",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "gutter-lg": "2rem",
        "margin-sm": "1rem",
        "margin": "1.5rem",
        "margin-lg": "4rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "display-hero": ["'Hanken Grotesk'", "sans-serif"],
        "display-hero-mobile": ["'Hanken Grotesk'", "sans-serif"],
        "headline-xl": ["'Hanken Grotesk'", "sans-serif"],
        "headline-xl-mobile": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "headline-sm": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
        "label-md": ["'Inter'", "sans-serif"],
        "label-sm": ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.035em", fontWeight: "500" }],
        "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.025em", fontWeight: "500" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "500" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.011em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.006em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      boxShadow: {
        "sm": "0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 3px -1px rgba(0, 0, 0, 0.05)",
        "md": "0 4px 6px -1px rgba(9, 9, 11, 0.05), 0 2px 4px -2px rgba(9, 9, 11, 0.04)",
        "lg": "0 10px 25px -5px rgba(9, 9, 11, 0.05), 0 8px 10px -6px rgba(9, 9, 11, 0.03)",
        "xl": "0 20px 30px -8px rgba(9, 9, 11, 0.08), 0 10px 15px -5px rgba(9, 9, 11, 0.04)",
        "2xl": "0 25px 50px -12px rgba(9, 9, 11, 0.12)",
      },
    },
  },
  plugins: [],
};
