import { EventWebsite, User } from '@/types';

export const mockCurrentUser: User = {
  id: 'usr_tempo_demo_01',
  name: 'Demo Creator',
  email: 'creator@tempo.atelier',
  avatarUrl: '',
  createdAt: '2026-01-01T00:00:00.000Z',
};

export const mockWebsites: EventWebsite[] = [
  {
    id: 'site-enrolldesk-portal',
    userId: 'usr_tempo_demo_01',
    templateId: 'enrolldesk-01',
    eventType: 'Student & Campus',
    title: 'EnrollDesk Classmate Hub',
    slug: 'enrolldesk-portal',
    status: 'published',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-28T14:30:00.000Z',
    expiresAt: null,
    isLifetime: true,
    tier: 'pro',
    metrics: {
      rsvpsCount: 0,
      viewsCount: 540,
      dietaryCount: 0,
      studentsCount: 18,
      isGuestListClosed: false,
    },
    eventData: {
      title: 'EnrollDesk Classmate Hub',
      tagline: 'Student Community & Classmate Portal',
      eventType: 'Student Portal',
      date: 'Fall & Spring Academic Year',
      targetDateIso: '2027-05-30T18:00:00.000Z',
      time: 'Always Active & Live',
      venue: 'Class of 2027 Portal',
      address: 'University Main Quad & Digital Lounge',
      note: 'Welcome to our private batch portal! Connect with peers across departments, find project partners by hobby, and stay updated with official notices.',
      photos: [
        {
          id: 'p-ed1',
          url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'campus-academic',
        palette: 'navy-gold-coral',
        typography: 'space-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: false,
        schedule: false,
        venue: false,
        gallery: false,
        rsvp: false,
        guestbook: false,
        classmatesDirectory: true,
        hobbyMatchmaker: true,
        studentEnrollment: true,
        noticesBoard: true,
        dynamicForms: true,
        memoryWall: true,
        adminDesk: true,
      },
      rsvpSettings: {
        enabled: false,
        allowMealSelection: false,
        allowDietaryNotes: false,
        allowSongRequests: false,
        allowPlusOnes: false,
      },
    },
  },
  {
    id: 'site-rahul-priya-wedding',
    userId: 'usr_tempo_demo_01',
    templateId: 'wedding-01',
    eventType: 'Wedding',
    title: 'Rahul & Priya',
    slug: 'rahul-and-priya',
    status: 'published',
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-09-20T14:30:00.000Z',
    expiresAt: null,
    isLifetime: true,
    metrics: {
      rsvpsCount: 84,
      viewsCount: 210,
      dietaryCount: 84,
      isGuestListClosed: false,
    },
    eventData: {
      title: 'Rahul & Priya',
      tagline: 'Save the Date',
      eventType: 'Wedding',
      date: '14 February 2027',
      targetDateIso: '2027-02-14T16:30:00.000Z',
      time: '4:30 PM Sunset Ceremony',
      venue: 'The Glasshouse at Palmetto Bay',
      address: '2480 Palmetto Bay Road, Carmel-by-the-Sea, California',
      note: 'Together with our beloved families, we invite you to join us in an intimate weekend celebrating love, laughter, and lifelong devotion overlooking the Pacific coast.',
      quote: {
        text: 'Whatever our souls are made of, his and mine are the same.',
        author: 'Emily Brontë',
      },
      photos: [
        {
          id: 'p-1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-0ni651F6U6aO1A08dR2obOwODyZv8xeFqmfd7ggij4bx3p1fv0wDMWaYpd-0j1YMc9pOrIHJx1GwzxDcU9IiKAN3fY7wKnl_9Z1_HV6F-gb_8dcn4Ag-AHVScZQxorNc5TSH7qAWT3clnQYcQSUL6q9nAY0x-A-FPeV77H4qIUsi9GUoYTAXHnqnZf3tzS-BM06p9hxhYPvMy6PTdFHwVHCb-gLve66veDG8dGAuzMiOPJfgv3_QmA',
          caption: 'Ceremony Portrait',
          isCover: true,
          altText: 'Rahul & Priya outdoor portrait',
        },
        {
          id: 'p-2',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrIZnqkwefPz1KdqtKxFO3vwxb_LKNfiJPyY8auvwOw_8_MMfo5_kQAimlIEl_FZEEu6mAXY2QHDkB271jZ8_-WrUd2HzJGcT_F0md37-bGMNqMkquCApmiVY1mC-W2KS0iMA8-OIh6kzDK547AlS_RP7kzdSjAeyu1DH0xEe7PRsVabJquOUAybyCWEXhbJIaKRWatN4BLiMJnm17Y0y5nxdAVAAxaTX6q6OgOF79S2NBPh3iQWCA_w',
          caption: 'Coffee in Hayes Valley',
        },
        {
          id: 'p-3',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMEmgepi6-xzdKwX3jsuYc1kGZScUVA7SLGYdW7dIjOH5G3ng-4MJK43ppWUMbWn7iSieCi_h1FVl7Hmd_4yjMEkQSFM6ppBXshrvM3tahp6kY7ovPcFeAa3F7U3CCk-x_S24Ntn99BEKudNPZyjBA_sQQwgKpGJimhluqsymgvguKSEYKkz1nE5iLhgs58SYojmng7iW5ufjLcevDfnYFXSGPjzoXiZkgayspgUIsZ4_cifG7vfP0dw',
          caption: 'Sunset Walk',
        },
        {
          id: 'p-4',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCE4aAhQ5y87Hru1Y2UG5u_SvBlAehqwM5pu28c9e4VhaSh0xmQQdVzZgYuDuHGDQNDo9WR2Q7WhNpAWPNOPloJflgpy5cPteZ8wnTUmdJ-U2AVAkn7Cyrpr5qH7V1UpboIjbp0uRlGCae9zO5l6xVCwx_7a4sGYCrEFiPZCacSbfi7ff_vcDVmRLSEhQbX-uapSezH--LSVTeg1Sce6bdY2ABvqy2ynE0DqUkkNAGZYIAvu_CUMCmUfQ',
          caption: 'Engagement Rings',
        },
      ],
      storyMilestones: [
        {
          id: 'm-1',
          date: 'October 2021',
          title: 'The First Coffee in Hayes Valley',
          description:
            'What was meant to be a thirty-minute introductory coffee stretched into a five-hour ramble through Golden Gate Park. By evening, we were already planning our next dinner.',
          icon: 'local_cafe',
        },
        {
          id: 'm-2',
          date: 'May 2023',
          title: 'A Shared Studio & Too Many Plants',
          description:
            'Combining record collections, learning each other’s grandmother recipes, and navigating the joyful chaos of our first sourdough baking phase together.',
          icon: 'cottage',
        },
        {
          id: 'm-3',
          date: 'September 2025',
          title: 'The Proposal on the Big Sur Cliffs',
          description:
            'Under the Pacific fog rolling over Garrapata State Park, Rahul asked on one knee. With salt spray in the air and teary laughter, Priya said yes before he could even finish the sentence.',
          icon: 'favorite',
        },
      ],
      schedule: [
        {
          id: 's-1',
          time: '4:00 PM',
          title: 'Welcome Drinks & Strings',
          description:
            'Arrive to botanical spritzes, sparkling cider, and an acoustic string trio playing in the glasshouse conservatory gardens.',
          location: 'Conservatory Lawn',
          icon: 'local_bar',
        },
        {
          id: 's-2',
          time: '4:30 PM',
          title: 'The Vow Ceremony',
          description:
            'An intimate union under floral canopies overlooking the Carmel Valley pine ridge. Please be seated by 4:20 PM.',
          location: 'The Main Terrace',
          icon: 'spa',
        },
        {
          id: 's-3',
          time: '6:00 PM',
          title: 'Sunset Dinner & Speeches',
          description:
            'Multi-course coastal harvest dining, heartfelt family toasts, and warm artisan breads shared family-style.',
          location: 'The Glass Atrium',
          icon: 'restaurant',
        },
        {
          id: 's-4',
          time: '8:30 PM',
          title: 'Dancing Under Lanterns',
          description:
            'Live DJ set, celebratory bhangra & soul classics, late-night chai, and sweet treats by the fire pits until midnight.',
          location: 'Courtyard & Pavilions',
          icon: 'celebration',
        },
      ],
      travelInfo: {
        venueName: 'The Glasshouse at Palmetto Bay',
        address: '2480 Palmetto Bay Road, Carmel-by-the-Sea, CA 93923',
        shuttleInfo: 'Complimentary pick-ups at 3:15 PM and 3:35 PM from the Carmel Mission Inn lobby.',
        hotelBlock: {
          hotelName: 'Carmel Mission Inn',
          description:
            'We have reserved a courtesy room block at the nearby Carmel Mission Inn and recommend booking by December 15, 2026 for the preferred celebratory rate.',
          groupCode: 'RP2027',
        },
        dressCode: {
          title: 'Dress Code: Festive Garden Formal',
          description:
            'Lightweight suits, floral cocktail dresses, or traditional celebratory festive attire (Kurtas, Sarees, Lehengas) are warmly encouraged. Evenings get crisp, so bring a cozy wrap!',
        },
        mapImageUrl:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDLAUqG0aCG7K6rb-mdQzOgJcps-SB50V96cFyXmvWUuQS_q7_L1SilKaFCePqRPSii6l8mdH_jYjVjJ23hXD33ySfLIjYep-7ZPJHoJ6JfS7koCulbcE2Sl6KhvMq0K60spIRtSAxL0u6CEyBqqE-3BgoMwhBvut5q8oEqFquywzKrmF6J3tzMFZw2RnIeOAW5ZT5yUPJff9DkJ2owtbg6zIZSC9J77J7Ji3pKMBXwnkdPjNTC70V3lg',
      },
      appearance: {
        atmosphere: 'classic-elegance',
        palette: 'terracotta-ivory-olive',
        typography: 'playfair-sans',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: true,
        schedule: true,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: {
        enabled: true,
        deadline: 'December 1, 2026',
        allowMealSelection: true,
        allowDietaryNotes: true,
        allowSongRequests: true,
        allowPlusOnes: true,
      },
    },
  },
  {
    id: 'site-emmas-25th',
    userId: 'usr_tempo_demo_01',
    templateId: 'birthday-01',
    eventType: 'Birthday',
    title: "Emma's 25th Birthday",
    slug: 'emma-turns-25',
    status: 'published',
    createdAt: '2026-09-01T12:00:00.000Z',
    updatedAt: '2026-09-24T18:00:00.000Z',
    expiresAt: '2026-10-13T00:00:00.000Z',
    isLifetime: false,
    metrics: {
      rsvpsCount: 26,
      viewsCount: 62,
      dietaryCount: 26,
      isGuestListClosed: true,
    },
    eventData: {
      title: "Emma's 25th Birthday",
      tagline: "Let's celebrate together",
      eventType: 'Birthday',
      date: '17 October 2026',
      targetDateIso: '2026-10-17T19:00:00.000Z',
      time: '7:30 PM Dinner & Toast',
      venue: 'The Amber Cellar Bistro',
      address: '420 Franklin Ave, Brooklyn, NY',
      note: "Turning a quarter of a century! Join me for an evening of warm comfort food, good drinks, and favorite people.",
      photos: [
        {
          id: 'p-b1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaup1JhzU1HUd2y0AKpT1_Ono_h1jOd-sueVQBQYVmRMu5S-rgzpoqdPzPSgGMQCtdaZWDba1F-54fc5cZKJxVBWcNHDNk8BXyAfxB6WODGemYtMDGtXIeywpKUy_zS1w2jIwOG7jappUchlK06i4U14xVmvcSojoevMbEzh8WjGmU2IAjrLFw8lpMibrr1VOJiyLO9gn33R0SoPVYx4NsBstAr5PS5JWS3Uy0N-0CMZW5W8VP-qjOpQ',
          caption: "Emma's Birthday dinner",
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'modernist-warmth',
        palette: 'terracotta-ivory-olive',
        typography: 'playfair-sans',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: false,
        schedule: true,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: true,
      },
      rsvpSettings: {
        enabled: true,
        deadline: '10 October 2026',
        allowMealSelection: true,
        allowDietaryNotes: true,
        allowSongRequests: true,
        allowPlusOnes: false,
      },
    },
  },
  {
    id: 'site-coffee-house-opening',
    userId: 'usr_tempo_demo_01',
    templateId: 'opening-01',
    eventType: 'Business Opening',
    title: 'The Coffee House Grand Opening',
    slug: 'the-coffee-house-opening',
    status: 'draft',
    createdAt: '2026-09-25T08:00:00.000Z',
    updatedAt: '2026-09-25T11:00:00.000Z',
    expiresAt: null,
    isLifetime: false,
    metrics: {
      rsvpsCount: 0,
      viewsCount: 0,
      dietaryCount: 0,
      isGuestListClosed: false,
    },
    eventData: {
      title: 'The Coffee House',
      tagline: 'Grand Opening Event',
      eventType: 'Business Opening',
      date: '20 October 2026',
      targetDateIso: '2026-10-20T09:00:00.000Z',
      time: '9:00 AM - 5:00 PM',
      venue: 'The Coffee House Flagship',
      address: '108 Market Street, Seattle, WA',
      note: 'We are thrilled to open our doors and welcome the community to our artisanal roastery and botanical cafe.',
      photos: [
        {
          id: 'p-c1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9xGgUsIj5wlELQ3K8BqaGvs_3ns-Jf1J865h_N-Yx3N205jkFX-zaV3UV2sz3AlIyKSP5tlcNYcqkc_-UJYrGnji-ZUsQQhMXugCjcI8DMosjP3V3HVXfO4ODnDoEvaG7KiDLvwZPV8WJgvznnm1tPCYr7ShujNpB8pC5Ye9pbOQRJ81-Rq4ErvsL1HFB-ccHsR1hCqbaq-MFmr_qFgcYFuy4bEEquAH4iMOnsXfKQayEqp6smAea8w',
          caption: 'Storefront and Roastery',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'sunlit-botanical',
        palette: 'sage-cream',
        typography: 'playfair-sans',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: {
        enabled: true,
        deadline: '18 October 2026',
        allowMealSelection: false,
        allowDietaryNotes: false,
        allowSongRequests: false,
        allowPlusOnes: true,
      },
    },
  },
  {
    id: 'site-enrolldesk-portal',
    userId: 'usr_tempo_demo_01',
    templateId: 'enrolldesk-01',
    eventType: 'Student & Campus',
    title: 'EnrollDesk Classmate Hub',
    slug: 'enrolldesk-portal',
    status: 'published',
    createdAt: '2026-09-28T09:00:00.000Z',
    updatedAt: '2026-09-28T14:00:00.000Z',
    expiresAt: null,
    isLifetime: true,
    metrics: {
      rsvpsCount: 28,
      viewsCount: 1420,
      dietaryCount: 0,
      isGuestListClosed: false,
      studentsCount: 18,
    },
    eventData: {
      title: 'EnrollDesk Classmate Hub',
      tagline: 'Student Community & Classmate Directory',
      eventType: 'Student Portal',
      date: 'Fall & Spring Academic Year',
      targetDateIso: '2027-05-30T18:00:00.000Z',
      time: 'Always Active & Live',
      venue: 'Class of 2027 Portal',
      address: 'University Main Quad & Digital Lounge',
      note: 'Welcome to our private batch portal! Connect with peers across departments, find project partners by hobby, and stay updated with official notices.',
      photos: [
        {
          id: 'p-ed1',
          url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
          caption: 'Campus Quad & Student Commons',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'campus-academic',
        palette: 'navy-gold-coral',
        typography: 'space-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: false,
        schedule: false,
        venue: false,
        gallery: false,
        rsvp: false,
        guestbook: false,
        classmatesDirectory: true,
        hobbyMatchmaker: true,
        studentEnrollment: true,
        noticesBoard: true,
        dynamicForms: true,
        memoryWall: true,
        adminDesk: true,
      },
      rsvpSettings: {
        enabled: false,
        allowMealSelection: false,
        allowDietaryNotes: false,
        allowSongRequests: false,
        allowPlusOnes: false,
      },
    },
  },
];
