import { TemplateDefinition, TemplateMetadata, EventCategory } from '@/types/template';
import { SolsticeSageTemplate } from './components/SolsticeSageTemplate';
import { AtelierNordTemplate } from './components/AtelierNordTemplate';
import { KomorebiDiningTemplate } from './components/KomorebiDiningTemplate';
import { FolioNoirTemplate } from './components/FolioNoirTemplate';
import { EnrollDeskPortal } from './components/EnrollDeskPortal';

/**
 * Built-in Atelier Template Registry for Tempo
 * Complete collection of curated templates with full metadata, specs, and default event data.
 */
export const templatesRegistry: TemplateDefinition[] = [
  {
    id: 'solstice-sage',
    name: 'Solstice & Sage',
    category: 'wedding',
    categoryLabel: 'Wedding & Celebration',
    subtitle: 'Elena & Marcus — Tuscany, Italy',
    description: 'An exquisite digital wedding invitation, schedule, and guest RSVP experience with timeless typography, natural organic textures, and seamless registry integration.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmlabs0X4K3WY9Dp_VDLzoDHbgyfIKmq0dv5eHK_fWLj5sFjlLZSyNyfM5ReCyQd8LqGJ6nTFuh1nF4vzuexAy2jeTojxZk0qBzaoY80f7jxGMZ3AGn6OA0tt6ca2HTw0Dg8bOJ7G0IUACxFHCh1MhrleNnES-8WMFaElh8mdUFmo8bC0HnksLIJT3Qrfn5k-xi9tyxxUQKrSkA-S16BsK8jTBXi0SZOKb96dRGmWNd0jI2TAad6I',
    badge: 'Wedding · Ceremony',
    author: 'Studio Forma',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBf49Bs6fSLexIzFjgpH_ZM9xiVnwW9T3DCFrNUqlCk4QCmb-3RrLscdJg-cwwK1fyBU-t__bxTuaMxr5RfRDbD16ttQu5S_UPJZZkmyBmxWZgBakTeF-bqrLMA0X5PcM1kGhCpCdFcjG8un-0ht9hhE1heGk24BpZiNpviIUWwrDSWJDhczkx84vEJ43AqJFiQ57sd8PzgxjUiBC-clhI5gBP9v-EeuNG71pvk_Mu-YfcW4cVB8s8',
    price: 29,
    priceLabel: '$29',
    isFree: false,
    rating: 4.98,
    reviewsCount: 42,
    techStack: 'HTML · Tailwind · Figma',
    version: 'v2.1 Stable',
    releaseDate: 'October 2024',
    isFeatured: true,
    tier: 'pro',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDxS67jRhs6SeYVFB1YXk49iyTDxMKVd1C7fax0xRQHbPxI9-XNqPcDb8D6aKYB8gAbKyhEbcatbG3JpuS9FCKvOPlbZhGVkcDYNsBTrUfQa2UadT4vwt9FzZxlrPo3BOSA7uNuId3D8SCGi7plgh42tfbYn3pbMv9w-LcYaAnkpH90R3uGez_gYEQKPk84SO9C__yg8k_WkY7CZxzoZjJxPS0fq90AcmR7Cn7gS-vDCvO5kKT_iIo',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAfkVwa9t-n1dR0Ds4Dx2v1Yz5BCE2AsokeX5b2CTFQxsMGKCMbXBY_qSy1USKxz_fEHtO1mbNJiueuH1RQnSXNo6g1jAaH60q3LHTbUcmgUFgCg6HLGOLR8GtkDK0_u86WQmnxyLth8jeiQ4L7GUG8ufoTXE9sL9RNjnG98gKgqafxMWiwJ_ONP6F2TNOH8K2NtLU9IHyRyvlsACJwwATS-DZ5rnJhUOGJBUJ0pXkoP_GPXwyLz4c',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA0I1mfYgDtL9YpudVifuEPjIXgaV2wdrOLO8XqU-B9mj_Li0qCw0BrB6MfnNzAITa0v-V3NRptJPM9r_ZmkDHWz6XNlG2VJ5AQqYkLdHVN76OLMEzL9XXgLUWjQdcalwmCehApYOz21n-bJtzPE0HcZedXiCb2vqKrtgp5Stmd1p_JPwkAmrShqJBLkQYvo7jv69jTqwLPbvm5wtbpS4Zr_mJRMDGgerbvMOJMVN65dKnV9RsDoKg',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBCh4ErbmxyLCCOUSo9LUJjpyYI9Sx62z404fC5woq9ZaxGgmpak8WzGUyYy3vKG0DiM_jhxkrtbRdC9srl8l99CGwGoLTMr1jS4nzD1ni4lh15JUBzHbNhH12SXpRLrs5VPpIeeELr4Hgh028ezGpL-ETHPUpQo57tvHdF-ZvNW1FyQ-Y-wp5ywnivo_rpz_h4SSBp5Sy60BL6McR2Dr-JK0RUwgfR3fVOHqqgF0S3o5Wk-B0RWKQ',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBZw3kf9dyT6cpRtjJRqh6Tq4FGEOmQzgE5cw60HcFRY99nzRd4Yc6qerSIC2SMQkohAHdu8H07XH0vz-d7fO8Q6CCqNk24CFeS53zFjRvNZ9XR1LWF8hPcidzhVx9-E9zd7RPJS8pk6ns8rZNPWMVpivagDQY5HuLtkxh7UsaxwFNZXhscqmmpX9saywxH66efZnfehHgS7hL-eAOgvX7couIwmodJME7OsP5M2GDBp0H2I4IIB4A',
    ],
    availableFunctions: ['RSVP Form', 'Dynamic Countdown', 'Photo Keepsake Gallery', 'Weekend Schedule & Maps', 'Gift Registry'],
    featuredDetails: {
      headline: 'Solstice & Sage Wedding Suite',
      subheadline: 'Architectural elegance and whisper-soft transitions for unforgettable unions.',
      description: 'A comprehensive digital production kit built with rigorous attention to typography, modularity, and rapid deployment. Includes interactive RSVP, sun calculation ticker, mobile gestures, and guest accommodations.',
      features: [
        'Instant RSVP validation with meal choices and plus-one logic',
        'Dynamic sunset and countdown clock aligned to venue coordinates',
        'Full Figma master tokens, CSS GPU acceleration, zero framework lock-in',
      ],
    },
    component: SolsticeSageTemplate,
    defaultData: {
      title: 'Elena & Marcus — Wedding Celebration',
      tagline: 'A celebration of love, light & gathered family',
      eventType: 'Wedding',
      date: 'October 18, 2025',
      targetDateIso: '2025-10-18T16:30:00.000Z',
      time: '4:30 PM Sunset Ceremony',
      venue: 'Villa Bellissima',
      address: 'Val d’Orcia, Tuscany, Italy',
      note: 'Join us beneath the Tuscan cypress trees as we exchange vows and gather our loved ones for an intimate weekend of celebration, fine wine, and joyful memories.',
      quote: {
        text: 'Where there is love there is life.',
        author: 'Leo Tolstoy',
      },
      photos: [
        {
          id: 'p-ss1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9srinSNn4zJZ_v_98MeZHCPZZfQ0bQMJ0s-mrx1JbU3TqDrBUogZrNofakDrYVLqME_Tb6RSrcZlwPdzYveBzwKXY0aWdf4qnvA-H1EFTOhWJYe7UGfEkyuBsT7oKuUgfi-kyMk23tbwr2WvH-1XXxEoq8jr4DB0sKUGPILxiIYJJF_SnWmpM0HagL3O4kKVUUIOOGI8C4PkA-dHYiRO9xqYTlHjENuKWGD14co_KoELaqgBuknM',
          caption: 'Golden Hour in Tuscany',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'classic-elegance',
        palette: 'terracotta-ivory-olive',
        typography: 'playfair-sans',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: true,
        schedule: true,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: {
        enabled: true,
        deadline: 'September 1, 2025',
        allowMealSelection: true,
        allowDietaryNotes: true,
        allowSongRequests: true,
        allowPlusOnes: true,
      },
    },
  },
  {
    id: 'atelier-nord',
    name: 'Atelier Nord',
    category: 'portfolio',
    categoryLabel: 'Architecture & Monograph',
    subtitle: 'Studio & Spatial Archive',
    description: 'Minimalist architectural monograph studio website mockup with sharp monochrome typography, stark brutalist concrete house photography, and asymmetric gallery grid.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6d_r6FNo0j_g9-iXt4B1Gb-gBv-i7LBjIrgo1ykS-NE7hAyPYhcfTpgwZDzOY-Z4xx_26ZEY5kk2yIy0FLR3ELrSSAM7e8lpqTZUpx6n2iknHVs1BeDBkDpAjGjeR6sEQOpign2N-53iCDulP1g4hOUBvCCCXsIThi-1VuTenEZehqUYoslI6McRsgxMVLlOzS97z1l0zl_UgngHwEzdI2HlYacqJpLQudwNPYuAzIuhUmqILdFQ',
    badge: "Curator's Choice",
    author: 'Nord Studio',
    price: 38,
    priceLabel: '$38',
    isFree: false,
    rating: 4.99,
    reviewsCount: 56,
    techStack: 'HTML · Tailwind · Zero Dependencies',
    version: 'v3.0',
    releaseDate: 'November 2024',
    isFeatured: true,
    tier: 'pro',
    availableFunctions: ['Project Archive Grid', 'High-res Lightbox', 'Studio Monograph', 'Contact & Booking'],
    component: AtelierNordTemplate,
    defaultData: {
      title: 'Atelier Nord Architecture',
      tagline: 'Pure layout geometry designed for creative direction agencies & monograph archives',
      eventType: 'Architecture Monograph',
      date: 'Available Now',
      targetDateIso: '2026-12-31T00:00:00.000Z',
      time: 'Open Exhibition',
      venue: 'Nordic Design Pavilion',
      address: 'Copenhagen & Stockholm',
      note: 'Monograph showcasing brutalist residential works, sustainable timber timber frame developments, and spatial research.',
      photos: [
        {
          id: 'p-an1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6d_r6FNo0j_g9-iXt4B1Gb-gBv-i7LBjIrgo1ykS-NE7hAyPYhcfTpgwZDzOY-Z4xx_26ZEY5kk2yIy0FLR3ELrSSAM7e8lpqTZUpx6n2iknHVs1BeDBkDpAjGjeR6sEQOpign2N-53iCDulP1g4hOUBvCCCXsIThi-1VuTenEZehqUYoslI6McRsgxMVLlOzS97z1l0zl_UgngHwEzdI2HlYacqJpLQudwNPYuAzIuhUmqILdFQ',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'minimalist-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: false,
        guestbook: false,
      },
      rsvpSettings: { enabled: false },
    },
  },
  {
    id: 'komorebi-eatery',
    name: 'Komorebi Eatery',
    category: 'restaurant',
    categoryLabel: 'Culinary & Dining',
    subtitle: 'Contemporary Omakase & Cocktail Lounge',
    description: 'Modern Japanese culinary website template with dark slate background, warm wood accents, ceramic dish presentation, and tasting menu reservation widget.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDi2XOK7vCTiCGviozLgg-AGlUOHngekg7Shx5BvmCyRh9bxu1BtR5VItHqNozogBCSE2PonNuR4i5O29F3xcCYS2uzb4McKLQLO_r72zJDPmWvN9uCxlje6tlvYf2sunCzGqtxYLjTXB42mUbzUd36BeDNTgTi5fuaaJGXq7QTCKjXqPDJ73aICLNisA11_0TxPbQpBUVREuzj32bQv4qbG0VNwGCHFSrltnfnIrHLrYw6oPLgBrE',
    badge: 'Dining & Hospitality',
    author: 'Kuroda Lab',
    price: 34,
    priceLabel: '$34',
    isFree: false,
    rating: 4.95,
    reviewsCount: 38,
    techStack: 'HTML · Tailwind · OpenTable Ready',
    version: 'v2.0',
    releaseDate: 'September 2024',
    isFeatured: true,
    tier: 'pro',
    availableFunctions: ['Tasting Menu Grid', 'Table Booking Form', 'Location & Hours', 'Private Dining'],
    component: KomorebiDiningTemplate,
    defaultData: {
      title: 'Komorebi Dining',
      tagline: 'Editorial Dining & Omakase Lounge',
      eventType: 'Restaurant Showcase',
      date: 'Open Tuesday – Sunday',
      targetDateIso: '2026-11-15T18:00:00.000Z',
      time: '5:30 PM - 11:00 PM',
      venue: 'Komorebi Kyoto Lounge',
      address: '74 Gion-machi Minamigawa, Kyoto',
      note: 'Seasonal 10-course tasting menus honoring seasonal Kyoto farm harvests and wild coastal seafood pairings.',
      photos: [
        {
          id: 'p-km1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDi2XOK7vCTiCGviozLgg-AGlUOHngekg7Shx5BvmCyRh9bxu1BtR5VItHqNozogBCSE2PonNuR4i5O29F3xcCYS2uzb4McKLQLO_r72zJDPmWvN9uCxlje6tlvYf2sunCzGqtxYLjTXB42mUbzUd36BeDNTgTi5fuaaJGXq7QTCKjXqPDJ73aICLNisA11_0TxPbQpBUVREuzj32bQv4qbG0VNwGCHFSrltnfnIrHLrYw6oPLgBrE',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'moody-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: {
        enabled: true,
        deadline: 'Always Open',
        allowMealSelection: true,
        allowDietaryNotes: true,
        allowSongRequests: false,
        allowPlusOnes: true,
      },
    },
  },
  {
    id: 'folio-noir',
    name: 'Folio Noir',
    category: 'portfolio',
    categoryLabel: 'Editorial Portfolio',
    subtitle: 'Showcase & High-Fashion Index',
    description: 'Dark aesthetic creative direction portfolio template preview, high fashion portrait photography, clean typographic case studies, and stark black layout with crisp white typography.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1pGwDKrzPnftoWaHNjz-d8zM8Bid4okYIn_eLybNBw4SzKC0ai7hVtf_vrY7IymcwJEzRn-BL5AiV9YT6AtF6S_FxuZrHVsjNepFixuWGKi41k-6q_fA8L4cEVTq0JOEI5pf_8pQshS3vFkyJo5CdCb1zJjU1ZjW_gQtNaojnouSovjrAbpUXpqNaRH5zvLlCMgt6ZSq3F32LrOst3_wAsLbS7iUV6Y9AmzktKCJrijgaidTZSTk',
    badge: 'Editorial · Free',
    author: 'Atelier Noire',
    price: 0,
    priceLabel: 'FREE',
    isFree: true,
    rating: 4.96,
    reviewsCount: 84,
    techStack: 'HTML · Tailwind · Figma',
    version: 'v1.4',
    releaseDate: 'October 2024',
    isFeatured: true,
    tier: 'free',
    availableFunctions: ['Case Study Grids', 'Video Backgrounds', 'Client List', 'Contact Modal'],
    component: FolioNoirTemplate,
    defaultData: {
      title: 'Folio Noir Portfolio',
      tagline: 'Editorial Creative Direction & Design Portfolio',
      eventType: 'Design Portfolio',
      date: '2025 Edition',
      targetDateIso: '2026-12-31T00:00:00.000Z',
      time: 'Live',
      venue: 'Design Studio Vault',
      address: 'Paris & London',
      note: 'A curated selection of creative direction, brand identity systems, and high fashion digital campaigns.',
      photos: [
        {
          id: 'p-fn1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1pGwDKrzPnftoWaHNjz-d8zM8Bid4okYIn_eLybNBw4SzKC0ai7hVtf_vrY7IymcwJEzRn-BL5AiV9YT6AtF6S_FxuZrHVsjNepFixuWGKi41k-6q_fA8L4cEVTq0JOEI5pf_8pQshS3vFkyJo5CdCb1zJjU1ZjW_gQtNaojnouSovjrAbpUXpqNaRH5zvLlCMgt6ZSq3F32LrOst3_wAsLbS7iUV6Y9AmzktKCJrijgaidTZSTk',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'minimalist-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: false,
        guestbook: false,
      },
      rsvpSettings: { enabled: false },
    },
  },
  {
    id: 'confetti-co',
    name: 'Confetti & Co.',
    category: 'birthday',
    categoryLabel: 'Birthday Invitation',
    subtitle: 'Playful Modern Party Hub',
    description: 'Festive modern birthday invitation template with pastel confetti accents, clean typography, countdown clock, photo dropzone, and RSVP form preview.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQ3fZgSOEFQx955WRyyGLZ5ZRSE53436nRNF06D7QP-zoOvaiqJSoj6-C9AWQ_L04cE2PGWnunOBvO47-KvLvgaKiz6Odx-L2J8L00AtKsnlmBV8bXOCVedsUrYspr9f1XSfPNHM9vXKTKuc3M0cTzPtGFezBUBE5ZTL9vuteyKijSxAjNn4THvusjSRFZm3W_YSUr84mC9pP0ySkU8ycY-wZfR4NKRf_G5d5DIYWVn0VHuZ5MvfM',
    badge: 'Birthday · Free',
    author: 'Studio Joy',
    price: 0,
    priceLabel: 'FREE',
    isFree: true,
    rating: 4.92,
    reviewsCount: 65,
    techStack: 'HTML5 · Tailwind · Figma',
    version: 'v2.0',
    releaseDate: 'September 2024',
    isFeatured: false,
    tier: 'free',
    availableFunctions: ['RSVP Form', 'Countdown Clock', 'Photo Gallery', 'Venue Map', 'Guest Notes'],
    component: SolsticeSageTemplate,
    defaultData: {
      title: 'Confetti & Co. Party',
      tagline: "Let's gather, celebrate, and make unforgettable memories",
      eventType: 'Birthday',
      date: 'November 22, 2025',
      targetDateIso: '2025-11-22T19:30:00.000Z',
      time: '7:30 PM Celebration',
      venue: 'The Loft on 4th',
      address: '240 4th Street, San Francisco, CA',
      note: 'Turning another fabulous chapter! Come for great music, sweet cocktails, and late-night laughs.',
      photos: [
        {
          id: 'p-cc1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQ3fZgSOEFQx955WRyyGLZ5ZRSE53436nRNF06D7QP-zoOvaiqJSoj6-C9AWQ_L04cE2PGWnunOBvO47-KvLvgaKiz6Odx-L2J8L00AtKsnlmBV8bXOCVedsUrYspr9f1XSfPNHM9vXKTKuc3M0cTzPtGFezBUBE5ZTL9vuteyKijSxAjNn4THvusjSRFZm3W_YSUr84mC9pP0ySkU8ycY-wZfR4NKRf_G5d5DIYWVn0VHuZ5MvfM',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'playful-terracotta',
        palette: 'terracotta',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: false,
        schedule: true,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: true,
      },
      rsvpSettings: {
        enabled: true,
        deadline: 'November 15, 2025',
        allowMealSelection: true,
        allowDietaryNotes: true,
        allowSongRequests: true,
        allowPlusOnes: true,
      },
    },
  },
  {
    id: 'studio-neon-30th',
    name: 'Studio Neon 30th',
    category: 'birthday',
    categoryLabel: 'Birthday Party RSVP',
    subtitle: 'Nocturnal Rooftop Celebration',
    description: 'Electric modern dark mode party invitation for milestone 30th celebrations with vivid neon accents, DJ lineup, and music player widget.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUtuxACK7eaAa3LhoR3Ux2orToUHlCNuXZp9ESVyDeMg_UJXbzeStgWBeYkLjnYUuNCErMwB0A7AlAwCRgYkmvFZEwEsGiO9unkv41zKWFogXbJLQYjFLO3CedXfSQoFc10kLyN0JNww7ty8FqfygzvDX9Q_jDOGt3kg6Kw4j2RHmK-TSJ_vUwu6QtAqzk_14LpsYA2PHvyVsVLzEI-Sq841Sfth2y5X92XwZcmuT0C_c4GYbL4SI',
    badge: 'Milestone · Free',
    author: 'Waveform',
    price: 0,
    priceLabel: 'FREE',
    isFree: true,
    rating: 4.97,
    reviewsCount: 51,
    techStack: 'HTML5 · Tailwind · Audio Integration',
    version: 'v1.8',
    releaseDate: 'October 2024',
    isFeatured: false,
    tier: 'free',
    availableFunctions: ['RSVP Form', 'DJ Lineup Card', 'Spotify Playlist Widget', 'Interactive Venue Map'],
    component: SolsticeSageTemplate,
    defaultData: {
      title: 'Studio Neon — Chapter 30',
      tagline: 'An electric evening of house grooves & good company',
      eventType: 'Birthday Party',
      date: 'December 12, 2025',
      targetDateIso: '2025-12-12T21:00:00.000Z',
      time: '9:00 PM - Late',
      venue: 'Skyline Warehouse Terrace',
      address: '500 E 7th St, Austin, TX',
      note: 'DJs, laser projection art, open bar, and good vibes only. Dress code: bold monochromatic or neon accents.',
      photos: [
        {
          id: 'p-sn1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUtuxACK7eaAa3LhoR3Ux2orToUHlCNuXZp9ESVyDeMg_UJXbzeStgWBeYkLjnYUuNCErMwB0A7AlAwCRgYkmvFZEwEsGiO9unkv41zKWFogXbJLQYjFLO3CedXfSQoFc10kLyN0JNww7ty8FqfygzvDX9Q_jDOGt3kg6Kw4j2RHmK-TSJ_vUwu6QtAqzk_14LpsYA2PHvyVsVLzEI-Sq841Sfth2y5X92XwZcmuT0C_c4GYbL4SI',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'minimalist-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: false,
        schedule: true,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: true,
      },
      rsvpSettings: {
        enabled: true,
        deadline: 'December 5, 2025',
        allowMealSelection: false,
        allowDietaryNotes: true,
        allowSongRequests: true,
        allowPlusOnes: true,
      },
    },
  },
  {
    id: 'bistro-verre',
    name: 'Bistro Verre',
    category: 'restaurant',
    categoryLabel: 'Restaurant & Bar',
    subtitle: 'Parisian Wine Bar & Bistro',
    description: 'Editorial Parisian wine bar and bistro restaurant landing page with high-contrast noir typography, tasting menu grid, intimate dining ambiance photos, and table booking.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuANjmqurnDusWihcPJaOqDYjher2s041i50dB6eNbbDrvlSGEWpECOuERbWXO3hIAxHdlsObRxsATtT9fTJzJeg1_tSIdMjqUaGTxrUWU2OLAjkMg_CPx5Y4s29t2-9hV_2LGsGRLZYgj8f3Egj5OgGtnwtv0L5WduHslsFwPZRBhKfYcRU2X40TsJ_O7NM1ysfEYLpCVYHagxkPAuuSMrq2VE51AY2cg8LPf4rOcQak4JyTmJzYEU',
    badge: 'Culinary · Free',
    author: 'Maison Bureau',
    price: 0,
    priceLabel: 'FREE',
    isFree: true,
    rating: 4.94,
    reviewsCount: 72,
    techStack: 'HTML · Tailwind · Mobile Menu',
    version: 'v2.2',
    releaseDate: 'August 2024',
    isFeatured: false,
    tier: 'free',
    availableFunctions: ['Digital Tasting Menu', 'Wine Cellar Index', 'Reservation Inquiries', 'Operating Schedule'],
    component: KomorebiDiningTemplate,
    defaultData: {
      title: 'Bistro Verre Paris',
      tagline: 'Natural wines, seasonal French plates & quiet evenings',
      eventType: 'Wine Bar & Bistro',
      date: 'Open Daily',
      targetDateIso: '2026-10-30T19:00:00.000Z',
      time: '6:00 PM - Midnight',
      venue: 'Bistro Verre Marais',
      address: '18 Rue de Turenne, 75004 Paris, France',
      note: 'A quiet tribute to natural biodynamic viticulture and timeless French gastronomy.',
      photos: [
        {
          id: 'p-bv1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuANjmqurnDusWihcPJaOqDYjher2s041i50dB6eNbbDrvlSGEWpECOuERbWXO3hIAxHdlsObRxsATtT9fTJzJeg1_tSIdMjqUaGTxrUWU2OLAjkMg_CPx5Y4s29t2-9hV_2LGsGRLZYgj8f3Egj5OgGtnwtv0L5WduHslsFwPZRBhKfYcRU2X40TsJ_O7NM1ysfEYLpCVYHagxkPAuuSMrq2VE51AY2cg8LPf4rOcQak4JyTmJzYEU',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'moody-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: { enabled: true, deadline: 'Open Daily' },
    },
  },
  {
    id: 'monochrome-archive',
    name: 'Monochrome Archive',
    category: 'portfolio',
    categoryLabel: 'Portfolio & Photography',
    subtitle: 'Brutalist Photography & Monograph',
    description: 'Brutalist architectural design portfolio website mockup showing asymmetric split grids, stark black and white photography of concrete buildings, and strict typography hierarchy.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD4iinDcHAmSV_Vh5q6BkvLWpSGlnRPPlxQtwjA7Box-UjDtvmEQRcWFblVy9Um42eYZR51RDvJtiwIJglkbSfZn1v9Ih7AJhvg9oowGiPcCmkdbbqQW--nEIC-gSvEGsvHGp6QyjWjO3yEBmEW0bZe_vrisCq9WjJ7_Is0XWpEULqlmWyQLBnI2119NcerdGSPvoTKHd-W-qw-g9_bNlcu_qvPQNif6D9IatFfR_d0j_xGaE_8TkQ',
    badge: 'Portfolio · Free',
    author: 'Form & Function',
    price: 0,
    priceLabel: 'FREE',
    isFree: true,
    rating: 4.96,
    reviewsCount: 93,
    techStack: 'HTML5 · Tailwind · Masonry Grid',
    version: 'v2.5',
    releaseDate: 'September 2024',
    isFeatured: false,
    tier: 'free',
    availableFunctions: ['Masonry Grid', 'Full View Lightbox', 'Author Bio & Awards', 'Direct Inquiry Form'],
    component: AtelierNordTemplate,
    defaultData: {
      title: 'Monochrome Archive',
      tagline: 'Brutalist spaces & monochrome photographic monographs',
      eventType: 'Photo Portfolio',
      date: 'Edition IV',
      targetDateIso: '2026-12-31T00:00:00.000Z',
      time: 'Live Monograph',
      venue: 'Digital Gallery',
      address: 'Zurich & Berlin',
      note: 'Exploring raw tactile surfaces, spatial geometry, and light interplay across concrete architectural masterpieces.',
      photos: [
        {
          id: 'p-ma1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD4iinDcHAmSV_Vh5q6BkvLWpSGlnRPPlxQtwjA7Box-UjDtvmEQRcWFblVy9Um42eYZR51RDvJtiwIJglkbSfZn1v9Ih7AJhvg9oowGiPcCmkdbbqQW--nEIC-gSvEGsvHGp6QyjWjO3yEBmEW0bZe_vrisCq9WjJ7_Is0XWpEULqlmWyQLBnI2119NcerdGSPvoTKHd-W-qw-g9_bNlcu_qvPQNif6D9IatFfR_d0j_xGaE_8TkQ',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'minimalist-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: false,
        guestbook: false,
      },
      rsvpSettings: { enabled: false },
    },
  },
  {
    id: 'vertex-cloud',
    name: 'Vertex Cloud',
    category: 'saas',
    categoryLabel: 'SaaS Product Landing',
    subtitle: 'Developer Infrastructure & Edge Hub',
    description: 'Technical SaaS enterprise application landing page featuring sleek dark slate dashboard mockups, data metric charts with turquoise line graph vectors, and crisp geometric sans typography.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7zqM46ZI3raTpJdrzFapmNi4txCHeTKWq2XCs1qC-HW9QW9SSjKKdoN0anjeGy3ZFe07_gm-ezVgl2NMHs2Jg77F7pQ__7S8cCIWVrglAU3R5k4dxmb74A1gJTVl_kS7iJJxLa15GwesN76ijHtSOfFoxnfOLrBmfKtAfmXip6GmLhIaBqaXOR1iP-WDJLvwphwI8nOkil9vSRdst-MU1QRhCTsgujMUUoIXvN2mNDfgBbjAaxWU',
    badge: 'SaaS · Infrastructure',
    author: 'Kelson & Co.',
    price: 49,
    priceLabel: '$49',
    isFree: false,
    rating: 4.98,
    reviewsCount: 39,
    techStack: 'HTML · Tailwind · React Components',
    version: 'v3.1',
    releaseDate: 'October 2024',
    isFeatured: false,
    tier: 'pro',
    availableFunctions: ['Interactive Pricing Toggles', 'Feature Bento Grid', 'Terminal Code Snippets', 'Email Waitlist'],
    component: AtelierNordTemplate,
    defaultData: {
      title: 'Vertex Cloud Infrastructure',
      tagline: 'Edge computing optimized for mission-critical modern engineering teams',
      eventType: 'Product Launch',
      date: 'v3 Launch',
      targetDateIso: '2026-10-01T00:00:00.000Z',
      time: 'Live',
      venue: 'Global Anycast Network',
      address: 'San Francisco, CA',
      note: 'Next-generation low-latency compute at the edge with zero-configuration deployments.',
      photos: [
        {
          id: 'p-vc1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7zqM46ZI3raTpJdrzFapmNi4txCHeTKWq2XCs1qC-HW9QW9SSjKKdoN0anjeGy3ZFe07_gm-ezVgl2NMHs2Jg77F7pQ__7S8cCIWVrglAU3R5k4dxmb74A1gJTVl_kS7iJJxLa15GwesN76ijHtSOfFoxnfOLrBmfKtAfmXip6GmLhIaBqaXOR1iP-WDJLvwphwI8nOkil9vSRdst-MU1QRhCTsgujMUUoIXvN2mNDfgBbjAaxWU',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'minimalist-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: false,
        guestbook: false,
      },
      rsvpSettings: { enabled: false },
    },
  },
  {
    id: 'botanica-suite',
    name: 'Botanica Suite',
    category: 'wedding',
    categoryLabel: 'Wedding & Estate',
    subtitle: 'Estate Garden & Country Affair',
    description: 'A rich heritage layout tailored for country garden affairs, estate gatherings, pressed fern botanical sketches, and classical serif headlines.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBTxh7MO3PP6kwBjZLDugRI_163A_hgAno07rWU-Hym7qC3pVZXOXWABADfRQPXJJMt7kffqhXqIi_LEEClfCMyVkP3GQT12qiOKsFX5hRf_I2DY0ZEmVIPdlXaKedtQawlWlsHnHzD8BM9OyHtl2Sdf75E-u53gqndaEeFXiPpdYMexBAxsB2CvKA70oSNxYEBGh5NwgvxLt-Q45MKArkeGBxeQUV2FkpLeaa3VKVe7xyHguc1syI',
    badge: 'Estate Wedding Kit',
    author: 'Studio Forma',
    price: 39,
    priceLabel: '$39',
    isFree: false,
    rating: 4.97,
    reviewsCount: 31,
    techStack: 'Figma + Astro + Tailwind',
    version: 'v2.4',
    releaseDate: 'September 2024',
    isFeatured: false,
    tier: 'pro',
    availableFunctions: ['Multi-day Event Itinerary', 'Lodging & Travel Directory', 'RSVP Multi-step Flow', 'Gift Registry'],
    component: SolsticeSageTemplate,
    defaultData: {
      title: 'Botanica Estate Celebration',
      tagline: 'A romantic gathering in the English countryside',
      eventType: 'Wedding',
      date: 'June 20, 2026',
      targetDateIso: '2026-06-20T15:00:00.000Z',
      time: '3:00 PM Lawn Ceremony',
      venue: 'Highclere Manor Gardens',
      address: 'Cotswolds, United Kingdom',
      note: 'Join us for champagne on the terrace, dinner under the glasshouse marquee, and dancing until sunrise.',
      photos: [
        {
          id: 'p-bs1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBTxh7MO3PP6kwBjZLDugRI_163A_hgAno07rWU-Hym7qC3pVZXOXWABADfRQPXJJMt7kffqhXqIi_LEEClfCMyVkP3GQT12qiOKsFX5hRf_I2DY0ZEmVIPdlXaKedtQawlWlsHnHzD8BM9OyHtl2Sdf75E-u53gqndaEeFXiPpdYMexBAxsB2CvKA70oSNxYEBGh5NwgvxLt-Q45MKArkeGBxeQUV2FkpLeaa3VKVe7xyHguc1syI',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'sunlit-botanical',
        palette: 'botanical-sage',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: true,
        schedule: true,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: {
        enabled: true,
        deadline: 'May 1, 2026',
        allowMealSelection: true,
        allowDietaryNotes: true,
        allowSongRequests: true,
        allowPlusOnes: true,
      },
    },
  },
  {
    id: 'aethel-rose',
    name: 'Aethel & Rose',
    category: 'wedding',
    categoryLabel: 'Micro-Celebration',
    subtitle: 'Intimate Elopement & City Hall',
    description: 'Monastic and romantic single-page invitation portal designed for intimate elopements, city hall ceremonies, and minimalist romantic announcements.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzf7zHAR_raCMwW74ekKzSfiImqEBiYQ-VZ33YAEjPlzhx86WUUEbVQqj8LijcyBdxPqrGrFKl2R9Dkz7BL2nJ9xPOWaeu7GVyherB5mesZPEZvZoUL1NOr0kMNUedQ1vn7cbAgV92OM4nmSHabva51hrN42424o5w7G4AOxQdPApSK0FH5ND-qfH9tvTraFqpFnyWLTm6kFnGVGfjKwlw6XFTlcNKcH1rb1ZcZekk0KVoqlWFPh4',
    badge: 'Micro-Celebration · Free',
    author: 'Studio Forma',
    price: 0,
    priceLabel: 'FREE',
    isFree: true,
    rating: 4.95,
    reviewsCount: 44,
    techStack: 'HTML + Tailwind',
    version: 'v1.2',
    releaseDate: 'October 2024',
    isFeatured: false,
    tier: 'free',
    availableFunctions: ['Single Page RSVP', 'Live Stream Link', 'Story Monograph', 'Keepsake Gallery'],
    component: SolsticeSageTemplate,
    defaultData: {
      title: 'Aethel & Rose — Elopement',
      tagline: 'An intimate commitment and quiet celebration',
      eventType: 'Elopement',
      date: 'September 14, 2025',
      targetDateIso: '2025-09-14T17:00:00.000Z',
      time: '5:00 PM Sunset',
      venue: 'San Francisco City Hall Rotunda',
      address: '1 Dr Carlton B Goodlett Pl, San Francisco, CA',
      note: 'We chose to exchange vows intimately and would love to share our photos and memories with you here.',
      photos: [
        {
          id: 'p-ar1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzf7zHAR_raCMwW74ekKzSfiImqEBiYQ-VZ33YAEjPlzhx86WUUEbVQqj8LijcyBdxPqrGrFKl2R9Dkz7BL2nJ9xPOWaeu7GVyherB5mesZPEZvZoUL1NOr0kMNUedQ1vn7cbAgV92OM4nmSHabva51hrN42424o5w7G4AOxQdPApSK0FH5ND-qfH9tvTraFqpFnyWLTm6kFnGVGfjKwlw6XFTlcNKcH1rb1ZcZekk0KVoqlWFPh4',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'classic-elegance',
        palette: 'warm-beige',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: { enabled: true, deadline: 'August 20, 2025' },
    },
  },
  {
    id: 'nordic-studio',
    name: 'Nordic Studio',
    category: 'business',
    categoryLabel: 'Agency & Consultancies',
    subtitle: 'Interior Architecture & Spatial Design',
    description: 'Scandinavian interior architecture agency website with expansive whitespace, timber wood tones, clean modern typography, and project case study grid.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrrq5kIV56UKLvdgPBhFhtWNg99lwkFFCQG574KUbnfvvuPchnWA6VuYPekn-A2_iDtyew4HEIzCp-xcTyxVLbR2lcOefB5HUdz7_z5eFQt9kj-J9MT2eH__9yt_i2xcg7YNAohdDi3V02bWSPmduqMeLaXVBjg9UeKkRE0tBz5y_SvY2PCcH9Gq8vpQ1IxnV6MwS6PThtGJjRj9HfkBdSHgV7vFjMqW0K48LS87Vs5ntiEKW0ZbQ',
    badge: 'Agency · Architecture',
    author: 'Oslo Grid',
    price: 34,
    priceLabel: '$34',
    isFree: false,
    rating: 4.93,
    reviewsCount: 29,
    techStack: 'HTML · Tailwind · Figma',
    version: 'v2.1',
    releaseDate: 'July 2024',
    isFeatured: false,
    tier: 'pro',
    availableFunctions: ['Case Studies Index', 'Studio Methodology', 'Services Breakdown', 'Contact & Booking'],
    component: AtelierNordTemplate,
    defaultData: {
      title: 'Nordic Studio Interior Architecture',
      tagline: 'Quiet spatial design engineered with light, timber and purpose',
      eventType: 'Agency Showcase',
      date: 'Available',
      targetDateIso: '2026-12-31T00:00:00.000Z',
      time: 'Always Open',
      venue: 'Oslo Studio Flagship',
      address: 'Pilestredet 75C, 0354 Oslo, Norway',
      note: 'Crafting residential and cultural interior environments across Scandinavia.',
      photos: [
        {
          id: 'p-ns1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrrq5kIV56UKLvdgPBhFhtWNg99lwkFFCQG574KUbnfvvuPchnWA6VuYPekn-A2_iDtyew4HEIzCp-xcTyxVLbR2lcOefB5HUdz7_z5eFQt9kj-J9MT2eH__9yt_i2xcg7YNAohdDi3V02bWSPmduqMeLaXVBjg9UeKkRE0tBz5y_SvY2PCcH9Gq8vpQ1IxnV6MwS6PThtGJjRj9HfkBdSHgV7vFjMqW0K48LS87Vs5ntiEKW0ZbQ',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'modernist-warmth',
        palette: 'warm-beige',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: false,
        guestbook: false,
      },
      rsvpSettings: { enabled: false },
    },
  },
  {
    id: 'craftsman-goods',
    name: 'Craftsman Goods',
    category: 'ecommerce',
    categoryLabel: 'Commerce & Storefront',
    subtitle: 'Bespoke Ceramics & Artifacts',
    description: 'Artisanal ceramic and bespoke home goods e-commerce storefront website layout with crisp product grid, earthy warm gray background, and refined typography.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtwNvdjW_E7ivxkPO_YHKLmH3NyRePWglz3DQ3R5JE8acwn98Fzk4Op-KrypkhVSL2Kj6ei-f1wO3psvr76FPahb3W3vn0BLCuNeFoD8aIZ44-X6xN1tJ649IgF0p-Dl6RObd40k9PiLhU_yCgtRD80nYN9M40Re1wb-BYMfF7ehLGejPqTMcD_czfMjHHrCfcjBvzFhmQiA7o1POyOWqHq-nC6j1mqEUDZ1AeOlXo-eAkc5wdPrc',
    badge: 'Storefront · Commerce',
    author: 'Potter & Clay',
    price: 49,
    priceLabel: '$49',
    isFree: false,
    rating: 4.96,
    reviewsCount: 35,
    techStack: 'HTML · Tailwind · Shopify/Stripe Ready',
    version: 'v2.0',
    releaseDate: 'October 2024',
    isFeatured: false,
    tier: 'pro',
    availableFunctions: ['Product Showcase Grid', 'Cart Drawer UI', 'Material Storytelling', 'Shipping & Care FAQ'],
    component: AtelierNordTemplate,
    defaultData: {
      title: 'Craftsman Ceramic Goods',
      tagline: 'Hand-thrown stoneware vessels and timeless tableware',
      eventType: 'Product Showcase',
      date: 'Fall Drop',
      targetDateIso: '2026-11-01T00:00:00.000Z',
      time: 'Store Open',
      venue: 'Artisanal Studio',
      address: 'Portland, OR',
      note: 'Each piece is hand-thrown on the potter’s wheel in small numbered studio batches.',
      photos: [
        {
          id: 'p-cg1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtwNvdjW_E7ivxkPO_YHKLmH3NyRePWglz3DQ3R5JE8acwn98Fzk4Op-KrypkhVSL2Kj6ei-f1wO3psvr76FPahb3W3vn0BLCuNeFoD8aIZ44-X6xN1tJ649IgF0p-Dl6RObd40k9PiLhU_yCgtRD80nYN9M40Re1wb-BYMfF7ehLGejPqTMcD_czfMjHHrCfcjBvzFhmQiA7o1POyOWqHq-nC6j1mqEUDZ1AeOlXo-eAkc5wdPrc',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'modernist-warmth',
        palette: 'warm-beige',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: true,
        schedule: false,
        venue: true,
        gallery: true,
        rsvp: false,
        guestbook: false,
      },
      rsvpSettings: { enabled: false },
    },
  },
  {
    id: 'academy-pro',
    name: 'Academy Pro',
    category: 'education',
    categoryLabel: 'Education & Curriculum',
    subtitle: 'Online Masterclass & Course Hub',
    description: 'Modern educational course curriculum website mockup showing interactive syllabus progress bar, video lesson player frame, instructor bio card, and student resources.',
    previewImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiNGOIiyv58OTXshZru5W8VmuHBkWlEdKYFbnpmMJA2mqyldI3cf4El6sLhRiVc5srApP6dI1GUUug8yLYJxZqoADVJoLPBq6x8ld4COj9T26WmY1oreWSYHxSTEooZqyqDDliB2hSlFFUCcHdIuK-F9CEXihg3JYEc_FOtTmBdYMXRf8M8X-91-fUEImjOP0JQeSqTpwLlMeccJqyYpfO-NmfBkV6DV4rWtizP-UhZF2xmzKFqFs',
    badge: 'Education · Free',
    author: 'LearnLab',
    price: 0,
    priceLabel: 'FREE',
    isFree: true,
    rating: 4.95,
    reviewsCount: 78,
    techStack: 'HTML5 · Tailwind · LMS Compatible',
    version: 'v1.9',
    releaseDate: 'September 2024',
    isFeatured: false,
    tier: 'free',
    availableFunctions: ['Syllabus Breakdown', 'Video Lesson Embeds', 'Student Testimonials', 'Enrollment Form'],
    component: AtelierNordTemplate,
    defaultData: {
      title: 'Academy Pro Masterclass',
      tagline: 'Master design systems and typographic discipline with industry directors',
      eventType: 'Masterclass Hub',
      date: 'Cohort 4 Enrollment',
      targetDateIso: '2026-11-01T00:00:00.000Z',
      time: 'Live Sessions',
      venue: 'Digital Classroom',
      address: 'Online Worldwide',
      note: 'Comprehensive 8-week intensive on building durable digital products and scalable design tokens.',
      photos: [
        {
          id: 'p-ap1',
          url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiNGOIiyv58OTXshZru5W8VmuHBkWlEdKYFbnpmMJA2mqyldI3cf4El6sLhRiVc5srApP6dI1GUUug8yLYJxZqoADVJoLPBq6x8ld4COj9T26WmY1oreWSYHxSTEooZqyqDDliB2hSlFFUCcHdIuK-F9CEXihg3JYEc_FOtTmBdYMXRf8M8X-91-fUEImjOP0JQeSqTpwLlMeccJqyYpfO-NmfBkV6DV4rWtizP-UhZF2xmzKFqFs',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'minimalist-noir',
        palette: 'monolith-zinc',
        typography: 'hanken-inter',
      },
      activeSections: {
        hero: true,
        countdown: true,
        story: true,
        schedule: true,
        venue: false,
        gallery: false,
        rsvp: true,
        guestbook: false,
      },
      rsvpSettings: { enabled: true, deadline: 'October 25, 2026' },
    },
  },
  {
    id: 'enrolldesk-01',
    name: 'EnrollDesk Portal',
    category: 'student',
    categoryLabel: 'Student & Campus',
    subtitle: 'Classmate Hub & Interactive Portal',
    description: 'Dynamic student space with classmate search, hobby matchmaker, self-enrollment, notices board, custom forms, memory wall, and admin 1-click broadcast.',
    previewImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    badge: 'Pro Interactive · Full Functions',
    author: 'Tempo Studio',
    price: 29,
    priceLabel: '$29',
    isFree: false,
    rating: 4.99,
    reviewsCount: 112,
    techStack: 'React · Tailwind · Supabase Realtime',
    version: 'v4.0',
    releaseDate: 'October 2024',
    isFeatured: true,
    tier: 'pro',
    availableFunctions: [
      'Classmate Directory with Search',
      'Hobby & Interest Matching Algorithm',
      'Student Self-Enrollment & Photo Cards',
      'Campus Notices & Urgent Broadcasts',
      'Dynamic Custom Forms & Batch Polls',
      'Classmate Memory Wall & Shoutouts',
      'Admin Control Desk & 1-Click WhatsApp Copy',
    ],
    component: EnrollDeskPortal,
    defaultData: {
      title: 'EnrollDesk Classmate Hub',
      tagline: 'Student Community & Classmate Portal',
      eventType: 'Student Portal',
      date: 'Academic Year 2026-2027',
      targetDateIso: '2027-05-30T18:00:00.000Z',
      time: 'Always Active & Live',
      venue: 'Class of 2027 Portal',
      address: 'University Main Quad & Digital Lounge',
      note: 'Welcome to our private batch portal! Connect with peers across departments, find project partners by hobby, and stay updated with official notices.',
      photos: [
        {
          id: 'p-ed1',
          url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
          isCover: true,
        },
      ],
      appearance: {
        atmosphere: 'campus-academic',
        palette: 'navy-gold-coral',
        typography: 'space-inter',
      },
      activeSections: {
        hero: true,
        countdown: false,
        story: false,
        schedule: false,
        venue: false,
        gallery: false,
        rsvp: false,
        guestbook: false,
        classmatesDirectory: true,
        hobbyMatchmaker: true,
        studentEnrollment: true,
        noticesBoard: true,
        dynamicForms: true,
        memoryWall: true,
        adminDesk: true,
      },
      rsvpSettings: { enabled: false },
      studentHub: {
        portalName: 'EnrollDesk Classmate Hub',
        tagline: 'Student Community & Classmate Portal',
        collegeOrBatchName: 'Class of 2027',
        adminPassword: 'admin123',
        departments: ['Computer Science', 'Design & Arts', 'Business & Finance', 'Mechanical Eng', 'Psychology', 'Biotech'],
        academicYears: ['1st Year (Freshman)', '2nd Year (Sophomore)', '3rd Year (Junior)', '4th Year (Senior)', 'Graduate / Alumni'],
        hobbiesList: ['Coding', 'Design & UI/UX', 'Music & Jamming', 'Gaming & Esports', 'Photography', 'Coffee & Cafes', 'Fitness & Gym', 'Anime & Manga', 'Reading', 'Travel & Hiking', 'Podcasts', 'Cooking'],
        students: [
          {
            id: 'st-1',
            fullName: 'Aarav Mehta',
            photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
            department: 'Computer Science',
            academicYear: '3rd Year (Junior)',
            instagram: 'aarav_codes',
            whatsapp: '+1 555-0192',
            gender: 'Male',
            hobbies: ['Coding', 'Gaming & Esports', 'Coffee & Cafes'],
            lookingFor: 'Hackathon Team',
            bio: 'Fullstack tinkerer, building indie web apps and looking for hackathon teammates!',
            enrolledAt: '2026-09-15',
          },
          {
            id: 'st-2',
            fullName: 'Zara Al-Mansoor',
            photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
            department: 'Design & Arts',
            academicYear: '3rd Year (Junior)',
            instagram: 'zara.creates',
            whatsapp: '+1 555-0143',
            gender: 'Female',
            hobbies: ['Design & UI/UX', 'Photography', 'Music & Jamming'],
            lookingFor: 'Study Buddy',
            bio: 'Visual designer exploring generative design and typography. Always down for coffee & playlist sharing.',
            enrolledAt: '2026-09-18',
          },
          {
            id: 'st-3',
            fullName: 'Marcus Vance',
            photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
            department: 'Business & Finance',
            academicYear: '2nd Year (Sophomore)',
            instagram: 'marcus_vance',
            whatsapp: '+1 555-0188',
            gender: 'Male',
            hobbies: ['Fitness & Gym', 'Podcasts', 'Travel & Hiking'],
            lookingFor: 'Project Partner',
            bio: 'Finance nerd & startup enthusiast. Let us connect for case competitions or gym sessions!',
            enrolledAt: '2026-09-20',
          },
        ],
        notices: [
          {
            id: 'n-1',
            title: 'Spring Campus Hackathon & Showcase',
            department: 'Computer Science',
            date: 'Oct 12, 2026',
            content: 'Registration is now open for our 36-hour annual hackathon with prizes sponsored by top tech innovators. Form teams of 2-4.',
            isUrgent: true,
            author: 'Student Council',
            category: 'Event',
          },
        ],
        forms: [
          {
            id: 'f-1',
            title: 'Class Project Partner Matching Form',
            description: 'Tell us your course codes, preferred time slots, and project domain to be automatically paired with a classmate.',
            department: 'All Departments',
            deadline: 'Oct 20, 2026',
            submissionsCount: 42,
            fields: [
              { id: 'f_name', label: 'Student Full Name', type: 'text', required: true, placeholder: 'e.g. Maya Chen' },
              { id: 'f_dept', label: 'Primary Course / Subject', type: 'text', required: true, placeholder: 'e.g. CS 301 - Distributed Systems' },
              { id: 'f_time', label: 'Preferred Meeting Hours', type: 'select', options: ['Weekday Evenings (6-9 PM)', 'Weekend Afternoons', 'Flexible / Async'], required: true },
            ],
          },
        ],
        shoutouts: [
          {
            id: 'sh-1',
            fromName: 'Zara',
            toName: 'Aarav',
            message: 'Huge thanks for debugging my React state issue before midnight submission! True legend.',
            tag: 'Study Hero',
            timestamp: '2 hours ago',
            likes: 14,
          },
        ],
        defaultCopyMessage: '🎓 Hey classmates! Join our private batch portal: ',
      },
    },
  },
];

export const getAllTemplates = (): TemplateMetadata[] => {
  return templatesRegistry.map(({ component: _c, defaultData: _d, ...meta }) => meta);
};

export const getTemplatesByCategory = (category: EventCategory): TemplateMetadata[] => {
  if (category === 'all') {
    return getAllTemplates();
  }
  return templatesRegistry
    .filter((t) => t.category === category)
    .map(({ component: _c, defaultData: _d, ...meta }) => meta);
};

export const getFreeTemplates = (): TemplateMetadata[] => {
  return templatesRegistry
    .filter((t) => t.isFree || t.price === 0)
    .map(({ component: _c, defaultData: _d, ...meta }) => meta);
};

export const getTemplateById = (id: string): TemplateMetadata | undefined => {
  const match = templatesRegistry.find((t) => t.id === id);
  if (!match) return undefined;
  const { component: _c, defaultData: _d, ...meta } = match;
  return meta;
};

export const getTemplateDefinition = (id: string): TemplateDefinition | undefined => {
  return templatesRegistry.find((t) => t.id === id);
};

export const getFeaturedTemplate = (): TemplateDefinition => {
  const featured = templatesRegistry.find((t) => t.isFeatured);
  return featured || templatesRegistry[0];
};

export const registerTemplate = (definition: TemplateDefinition): void => {
  const existingIdx = templatesRegistry.findIndex((t) => t.id === definition.id);
  if (existingIdx !== -1) {
    templatesRegistry[existingIdx] = definition;
  } else {
    templatesRegistry.push(definition);
  }
};
